### ISSUE TITLE
Compile error on macOS 15.1.1

### ISSUE THREAD

**Issue by akira-okumura** [ROBAST/ROBAST#38]
**Describe the bug**
ROBAST v3.2.1 does not compile on macOS Sequoia 15.1.1.

**To Reproduce**
1. Install ROOT 6.32.08 from the source.
2. Build ROBAST with the make command.
3. It emits the following error messages.

```
Compiling src/AMultilayer.cxx
c++ -O2 -pipe -Wall -W -Woverloaded-virtual -stdlib=libc++ -pthread -std=c++17 -m64 -I/usr/local/root-6.32.08_install/include  -Wall -g -Iinclude -c src/AMultilayer.cxx -o src/AMultilayer.o
src/AMultilayer.cxx:179:56: error: 'this' cannot be implicitly captured in this context
  179 |   auto n_list = [](std::size_t i) { return std::get<0>(fLayers[i]);}; // (n, k)
      |                                                        ^
src/AMultilayer.cxx:179:18: note: explicitly capture 'this'
  179 |   auto n_list = [](std::size_t i) { return std::get<0>(fLayers[i]);}; // (n, k)
      |                  ^
      |                  this
src/AMultilayer.cxx:180:56: error: 'this' cannot be implicitly captured in this context
  180 |   auto d_list = [](std::size_t i) { return std::get<1>(fLayers[i]);}; // thickness
      |                                                        ^
src/AMultilayer.cxx:180:18: note: explicitly capture 'this'
  180 |   auto d_list = [](std::size_t i) { return std::get<1>(fLayers[i]);}; // thickness
      |                  ^
      |                  this
src/AMultilayer.cxx:181:56: error: 'this' cannot be implicitly captured in this context
  181 |   auto c_list = [](std::size_t i) { return std::get<2>(fLayers[i]);}; // coherent or not
      |                                                        ^
src/AMultilayer.cxx:181:18: note: explicitly capture 'this'
  181 |   auto c_list = [](std::size_t i) { return std::get<2>(fLayers[i]);}; // coherent or not
      |                  ^
      |                  this
src/AMultilayer.cxx:189:32: error: no matching constructor for initialization of 'std::vector<std::complex<Double_t>>' (aka 'vector<complex<double>>')
  189 |         ongoing_stack_n_list = std::vector<std::complex<Double_t>>{n_list(i - 1), n_list(i)};
      |                                ^                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:427:64: note: candidate constructor not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'size_type' (aka 'unsigned long') for 1st argument
  427 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI explicit vector(size_type __n, const allocator_type& __a);
      |                                                                ^      ~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:429:55: note: candidate constructor not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'size_type' (aka 'unsigned long') for 1st argument
  429 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(size_type __n, const value_type& __x);
      |                                                       ^      ~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:505:3: note: candidate constructor not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'const vector<complex<double>>' for 1st argument
  505 |   vector(const vector& __x, const __type_identity_t<allocator_type>& __a);
      |   ^      ~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:512:3: note: candidate constructor not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'initializer_list<value_type>' (aka 'initializer_list<std::complex<double>>') for 1st argument
  512 |   vector(initializer_list<value_type> __il, const allocator_type& __a);
      |   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:528:3: note: candidate constructor not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'vector<complex<double>>' for 1st argument
  528 |   vector(vector&& __x, const __type_identity_t<allocator_type>& __a);
      |   ^      ~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:445:55: note: candidate template ignored: substitution failure [with _InputIterator = typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type]: no type named 'reference' in 'std::iterator_traits<std::shared_ptr<ARefractiveIndex>>'
  443 |                               is_constructible<value_type, typename iterator_traits<_InputIterator>::reference>::value,
      |                                                                                                      ~~~~~~~~~
  444 |                           int> = 0>
  445 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(_InputIterator __first, _InputIterator __last);
      |                                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:458:55: note: candidate template ignored: substitution failure [with _ForwardIterator = typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type]: no type named 'reference' in 'std::iterator_traits<std::shared_ptr<ARefractiveIndex>>'
  456 |                         is_constructible<value_type, typename iterator_traits<_ForwardIterator>::reference>::value,
      |                                                                                                  ~~~~~~~~~
  457 |                     int> = 0>
  458 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(_ForwardIterator __first, _ForwardIterator __last);
      |                                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:417:64: note: candidate constructor not viable: requires single argument '__a', but 2 arguments were provided
  417 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI explicit vector(const allocator_type& __a)
      |                                                                ^      ~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:425:64: note: candidate constructor not viable: requires single argument '__n', but 2 arguments were provided
  425 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI explicit vector(size_type __n);
      |                                                                ^      ~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:503:55: note: candidate constructor not viable: requires single argument '__x', but 2 arguments were provided
  503 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(const vector& __x);
      |                                                       ^      ~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:509:55: note: candidate constructor not viable: requires single argument '__il', but 2 arguments were provided
  509 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(initializer_list<value_type> __il);
      |                                                       ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:520:55: note: candidate constructor not viable: requires single argument '__x', but 2 arguments were provided
  520 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector(vector&& __x)
      |                                                       ^      ~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:433:3: note: candidate constructor template not viable: requires 3 arguments, but 2 were provided
  433 |   vector(size_type __n, const value_type& __x, const allocator_type& __a)
      |   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:451:3: note: candidate constructor template not viable: requires 3 arguments, but 2 were provided
  451 |   vector(_InputIterator __first, _InputIterator __last, const allocator_type& __a);
      |   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:466:3: note: candidate constructor template not viable: requires 3 arguments, but 2 were provided
  466 |   vector(_ForwardIterator __first, _ForwardIterator __last, const allocator_type& __a);
      |   ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:415:55: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
  415 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI vector()
      |                                                       ^
src/AMultilayer.cxx:196:30: error: no matching member function for call to 'push_back'
  196 |         ongoing_stack_n_list.push_back(n_list(i));
      |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:637:60: note: candidate function not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'const value_type' (aka 'const std::complex<double>') for 1st argument
  637 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(const_reference __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:639:60: note: candidate function not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'value_type' (aka 'std::complex<double>') for 1st argument
  639 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(value_type&& __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~
src/AMultilayer.cxx:198:24: error: no matching member function for call to 'push_back'
  198 |         stack_from_all.push_back(std::make_pair(stack_index, within_stack_index));
      |         ~~~~~~~~~~~~~~~^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:637:60: note: candidate function not viable: no known conversion from 'pair<typename __unwrap_ref_decay<unsigned long &>::type, typename __unwrap_ref_decay<unsigned long &>::type>' (aka 'pair<unsigned long, unsigned long>') to 'const value_type' (aka 'const std::vector<unsigned long>') for 1st argument
  637 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(const_reference __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:639:60: note: candidate function not viable: no known conversion from 'pair<typename __unwrap_ref_decay<unsigned long &>::type, typename __unwrap_ref_decay<unsigned long &>::type>' (aka 'pair<unsigned long, unsigned long>') to 'value_type' (aka 'std::vector<unsigned long>') for 1st argument
  639 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(value_type&& __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~
src/AMultilayer.cxx:202:22: error: no matching member function for call to 'push_back'
  202 |       stack_from_all.push_back(kNAN);
      |       ~~~~~~~~~~~~~~~^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:637:60: note: candidate function not viable: no known conversion from 'const Double_t' (aka 'const double') to 'const value_type' (aka 'const std::vector<unsigned long>') for 1st argument
  637 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(const_reference __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:639:60: note: candidate function not viable: no known conversion from 'const Double_t' (aka 'const double') to 'value_type' (aka 'std::vector<unsigned long>') for 1st argument
  639 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(value_type&& __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~
src/AMultilayer.cxx:211:22: error: no matching member function for call to 'push_back'
  211 |         stack_d_list.push_back(ongoing_stack_d_list);
      |         ~~~~~~~~~~~~~^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:637:60: note: candidate function not viable: no known conversion from 'std::vector<Double_t>' (aka 'vector<double>') to 'const value_type' (aka 'const double') for 1st argument
  637 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(const_reference __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:639:60: note: candidate function not viable: no known conversion from 'std::vector<Double_t>' (aka 'vector<double>') to 'value_type' (aka 'double') for 1st argument
  639 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(value_type&& __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~
src/AMultilayer.cxx:212:30: error: no matching member function for call to 'push_back'
  212 |         ongoing_stack_n_list.push_back(n_list(i));
      |         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:637:60: note: candidate function not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'const value_type' (aka 'const std::complex<double>') for 1st argument
  637 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(const_reference __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:639:60: note: candidate function not viable: no known conversion from 'typename tuple_element<0UL, tuple<shared_ptr<ARefractiveIndex>, double, int>>::type' (aka 'std::shared_ptr<ARefractiveIndex>') to 'value_type' (aka 'std::complex<double>') for 1st argument
  639 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(value_type&& __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~
src/AMultilayer.cxx:213:22: error: no matching member function for call to 'push_back'
  213 |         stack_n_list.push_back(ongoing_stack_n_list);
      |         ~~~~~~~~~~~~~^~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:637:60: note: candidate function not viable: no known conversion from 'std::vector<std::complex<Double_t>>' (aka 'vector<complex<double>>') to 'const value_type' (aka 'const std::shared_ptr<ARefractiveIndex>') for 1st argument
  637 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(const_reference __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1/vector:639:60: note: candidate function not viable: no known conversion from 'std::vector<std::complex<Double_t>>' (aka 'vector<complex<double>>') to 'value_type' (aka 'std::shared_ptr<ARefractiveIndex>') for 1st argument
  639 |   _LIBCPP_CONSTEXPR_SINCE_CXX20 _LIBCPP_HIDE_FROM_ABI void push_back(value_type&& __x);
      |                                                            ^         ~~~~~~~~~~~~~~~~
src/AMultilayer.cxx:485:47: warning: unused parameter 'polarization' [-Wunused-parameter]
  485 | void AMultilayer::IncoherentTMM(EPolarization polarization,
      |                                               ^
src/AMultilayer.cxx:486:56: warning: unused parameter 'th_0' [-Wunused-parameter]
  486 |                                 std::complex<Double_t> th_0, Double_t lam_vac,
      |                                                        ^
src/AMultilayer.cxx:486:71: warning: unused parameter 'lam_vac' [-Wunused-parameter]
  486 |                                 std::complex<Double_t> th_0, Double_t lam_vac,
      |                                                                       ^
src/AMultilayer.cxx:487:43: warning: unused parameter 'reflectance' [-Wunused-parameter]
  487 |                                 Double_t& reflectance,
      |                                           ^
src/AMultilayer.cxx:488:43: warning: unused parameter 'transmittance' [-Wunused-parameter]
  488 |                                 Double_t& transmittance) const {
      |                                           ^
5 warnings and 10 errors generated.
make: *** [src/AMultilayer.o] Error 1
```

**Expected behavior**
Should compile.

**Environment (please complete the following information):**
 - OS: macOS 15.1.1
 - ROOT: 6.32.08
 - ROBAST: v3.2.1
